### ISSUE TITLE
Error during deployment using BTDF

### ISSUE THREAD

**Issue by tfabraham** [BTDF/DeploymentFramework#192]
Hi,
 
i have created a simple application with orchestrations, schemas and maps with in different projects.
 
changed the .btproj file according to the project and deployed the application and got an error that no binding file available, as you have mention for first time binding file as to be created manually,exported binging file form biztalk admin console and saved it in <projectname>.PortBindingsMaster.xml.
 
Also made the following changes in .btproj file
 
<UsingMasterBindings>True</UsingMasterBindings>
<ApplyXmlEscape>False</ApplyXmlEscape>

<IncludeMessagingBindings>False</IncludeMessagingBindings>
 
presently i am getting below mentioned error 
 
StartApplication:
  Starting BTDFProject application at 01-19-11 11:54:55.
  Note: Starting the app may take 5-10 secs PER ORCHESTRATION. Please wait...
  (Retry count 0)
  Starting BTDFProject application...
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1674,5): error : Could not enlist orchestration 'BTDFProject.Orchestration.BTDFOrchestration,BTDFProject.Orchestration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7434600497e0e724'. Could not enlist orchestration 'BTDFProject.Orchestration.BTDFOrchestration'. All orchestration ports must be bound and the host must be set.
Done Building Project "E:\Malathi\BTDFProject\BTDFProject\BTDFProject.Deployment\BTDFProject.Deployment.btdfproj" (Deploy target(s)) -- FAILED.
 
Build FAILED.
 
"E:\Malathi\BTDFProject\BTDFProject\BTDFProject.Deployment\BTDFProject.Deployment.btdfproj" (Deploy target) (1) ->
(StartApplication target) -> 
  C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1674,5): error : Could not enlist orchestration 'BTDFProject.Orchestration.BTDFOrchestration,BTDFProject.Orchestration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7434600497e0e724'. Could not enlist orchestration 'BTDFProject.Orchestration.BTDFOrchestration'. All orchestration ports must be bound and the host must be set.
 
0 Warning(s)
1 Error(s)

 
Time Elapsed 00:00:28.94
 
Could you tell me what has to be done
i have also tried making <IncludeMessagingBindings>true</IncludeMessagingBindings>but then it gives portbindings.xml file not found error.
 
further i am trying to create PortBindings.xml file from PortBindingsMaster.xml using preprocess biztalk binding.
 
could you tell me which binding file as to be created first PortBindings.xml or PortBindingMaster.xml
 
thanks in advance.

#### This work item was migrated from CodePlex
CodePlex work item ID: '7827'
Vote count: '1'

**Comment by tfabraham** [comment]
[tfabraham@1/19/2011]
When <UsingMasterBindings> is true you will also want <IncludeMessagingBindings> true, and you must create PortBindingsMaster.xml first.  PortBindings.xml will be created by combining values from your settings spreadsheet with the PortBindingsMaster.xml (the template).

**Comment by tfabraham** [comment]
[malathy@1/19/2011]
Thanks.my understanding was also the same,but I dont understand why iam getting this error.while deployment I think the my project is not making use of portbindingsmaster.xml.how to make it use

**Comment by tfabraham** [comment]
[tfabraham@1/19/2011]
If you have IncludeMessagingBindings set to True and you are still receiving an error, please post the new error here.  Thanks.

**Comment by tfabraham** [comment]
[malathy@1/19/2011]
thanks.

i have made <IncludeMessagingBindings> true and <UsingMasterBindings>True it gives me the following error

---------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------
Starting build...
C:\Windows\Microsoft.NET\Framework\v3.5\MSBuild.exe "E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Deployment\BTDFSolution.Deployment.btdfproj" /nologo /t:Deploy /p:Configuration=Release

Build started 1/20/2011 12:26:47 PM.
Project "E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Deployment\BTDFSolution.Deployment.btdfproj" on node 0 (Deploy target(s)).
  Running on Windows V61
  Detected IIS 7
  Detected 64-bit OS
GetSoftwarePaths:
  Using .NET Framework Install Path 'C:\Windows\Microsoft.NET\Framework\v2.0.50727'.
  Using BizTalk Install Path 'C:\Program Files (x86)\Microsoft BizTalk Server 2009\'.
  Using Deployment Framework Install Path 'C:\Program Files (x86)\Deployment Framework for BizTalk\5.0\'.
  Using Deployment Framework Tools Path 'C:\Program Files (x86)\Deployment Framework for BizTalk\5.0\Framework\DeployTools'.
  Using BizTalk ESB Toolkit Install Path 'E:\ESBToolkit\'.
InitSettingsFilePath:
  Using settings file E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Deployment\EnvironmentSettings\local_settings.xml
ExportSettings:
  Environment Settings Spreadsheet to XML Exporter 1.5.1
  [http://EnvSettingsManager.codeplex.com]
  Copyright (C) 2007-10 Thomas F. Abraham.  All Rights Reserved.
  
  Importing from SettingsFileGenerator.xml...
  
  Output format is XmlPreprocess (multi-file).
  
  Exporting to local_settings.xml...
  Exporting to DEVL_settings.xml...
  Exporting to QA_settings.xml...
  Exporting to PROD_settings.xml...
  
  Finished.
InitializeAppName:
  BizTalk Application Name is BTDFSolution
PreprocessBindings:
  Clearing file attributes for 'BTDFSolution.PortBindings.xml'.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : A task error has occured.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Message              = The resource string "FileNotFound.Exception" for the "SetValue" task cannot be found. Confirm that the resource name "FileNotFound.Exception" is correctly spelled, and the resource exists in the task's assembly.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Value                = BTDFSolution
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : IgnoreNoMatchFailure = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Force                = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : XPath                = //ApplicationName
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Path                 = BTDFSolution.PortBindings.xml
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Namespaces           = <null>
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : 
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, Exception innerException, String resourceName, Object arg0, Object arg1)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatResourceString(String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.BaseXmlFileTask.OpenXmlFile(String path)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.SetValue.InternalExecute()
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.TaskBase.Execute()
Done Building Project "E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Deployment\BTDFSolution.Deployment.btdfproj" (Deploy target(s)) -- FAILED.

Build FAILED.

"E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Deployment\BTDFSolution.Deployment.btdfproj" (Deploy target) (1) ->
(PreprocessBindings target) -> 
  C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : A task error has occured.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Message              = The resource string "FileNotFound.Exception" for the "SetValue" task cannot be found. Confirm that the resource name "FileNotFound.Exception" is correctly spelled, and the resource exists in the task's assembly.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Value                = BTDFSolution
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : IgnoreNoMatchFailure = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Force                = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : XPath                = //ApplicationName
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Path                 = BTDFSolution.PortBindings.xml
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Namespaces           = <null>
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : 
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, Exception innerException, String resourceName, Object arg0, Object arg1)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatResourceString(String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.BaseXmlFileTask.OpenXmlFile(String path)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.SetValue.InternalExecute()
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.TaskBase.Execute()

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.81
-----------------------------------------------------------------------------------------------------------

i dont understand why it is searching for PortBindings.xml when PortBindingMaster.xml is present.

What could be my mistake.

**Comment by tfabraham** [comment]
[tfabraham@1/19/2011]
To verify that this is not an issue with your custom file names, could you please comment out your <PortBindings> and/or <PortBindingsMaster> property definitions in your .btdfproj, and rename your master file back to PortBindingsMaster.xml (the default name)?  Then try the deployment again and see if the results change.
If that does not work either, could you please post your .btdfproj file contents?

**Comment by tfabraham** [comment]
[malathy@1/20/2011]
thanks.

i have changed the names of PortBindings.xml and PortBindingMaster.xml to their default in the target file,but i don't understand what your telling to comment in .btdfproj file,i am unble to find the PortBindings property in this .btdfproj file. Below is my projects .btdfproj file


<?xml version="1.0" encoding="utf-8"?>

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Deploy">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <Platform Condition="'$(Platform)' == ''">x86</Platform>
    <SchemaVersion>1.0</SchemaVersion>
    <ProjectName>BTDFSolution</ProjectName>
    <ProjectVersion>1.0</ProjectVersion>
	<IncludeMessagingBindings>True</IncludeMessagingBindings>
    <UsingMasterBindings>True</UsingMasterBindings>
	<ApplyXmlEscape>False</ApplyXmlEscape>
  </PropertyGroup>
  <PropertyGroup>
    
    <ProductId>3da3ed8d-e517-438d-b735-8fdb3474a427</ProductId>
    <ProductUpgradeCode>9ec621d3-efee-4336-a820-172a236787f0</ProductUpgradeCode>
    <ProductName>BTDFSolution for BizTalk</ProductName>
    <ProductVersion>1.0.0</ProductVersion>
    <Manufacturer>Deployment Framework User</Manufacturer>
    <PackageDescription>BTDFSolution</PackageDescription>
    <PackageComments>BTDFSolution</PackageComments>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DeploymentFrameworkTargetsPath>$(MSBuildExtensionsPath)\DeploymentFrameworkForBizTalk\5.0\</DeploymentFrameworkTargetsPath>
    <OutputPath>bin\Debug\</OutputPath>
    <DeployPDBsToGac>false</DeployPDBsToGac>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DeploymentFrameworkTargetsPath>$(MSBuildExtensionsPath)\DeploymentFrameworkForBizTalk\5.0\</DeploymentFrameworkTargetsPath>
    <OutputPath>bin\Release\</OutputPath>
    <DeployPDBsToGac>false</DeployPDBsToGac>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Server'">
    <DeploymentFrameworkTargetsPath>Framework\</DeploymentFrameworkTargetsPath>
    
    <DeployPDBsToGac>true</DeployPDBsToGac>
  </PropertyGroup>
  <ItemGroup>
    <Schemas Include="BTDFSolution.Schemas.dll">
      <LocationPath>E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Schemas\bin\Debug</LocationPath>
    </Schemas>
	  <Transforms Include="BTDFSolution.Transforms.dll">
		  <LocationPath>E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Transforms\bin\Debug</LocationPath>
	  </Transforms>
	  <Orchestrations Include="BTDFSolution.Orchestrations.dll">
		  <LocationPath>E:\Malathi\BTDFSolution\BTDFSolution\BTDFSolution.Orchestrations\bin\Debug</LocationPath>
	  </Orchestrations>
  </ItemGroup>
  <Import Project="$(DeploymentFrameworkTargetsPath)BizTalkDeploymentFramework.targets" />
  
  <Target Name="CustomRedist">
  </Target>
</Project>

kindly tell me what else can be tried.

**Comment by tfabraham** [comment]
[UnknownUser@1/20/2011]

**Comment by tfabraham** [comment]
[UnknownUser@2/21/2013]

**Comment by tfabraham** [comment]
[UnknownUser@5/16/2013]

**Comment by tfabraham** [comment]
**Issue closed by _tfabraham_ with comment**
Continue discussion in Discussions or issue about error with MSI deploy
