### ISSUE TITLE
Error during deployment of MSI file

### ISSUE THREAD

**Issue by tfabraham** [BTDF/DeploymentFramework#193]
Hi,
 
I have created the MSI file for my project using "build server deploy MSI" option in VS tool.The bin and obj folders and the MSI files got created successfully.When i tried to install and deploy the created msi file,it got installed successfully and i checked the check box used for deployment,it as asked for the domain name and the configuration file (Local_settings.xml),at that it ended with an error .
 
i have attached the screen shot of the error.Kindly guide me to overcome this issue.
 
Thanks in Advance.

#### Attachments
[Error.jpg](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=biztalkdeployment&WorkItemId=7829&FileAttachmentId=2461)

#### This work item was migrated from CodePlex
CodePlex work item ID: '7829'
Vote count: '1'

**Comment by tfabraham** [comment]
[tfabraham@1/19/2011]
Are you explicitly setting the property <PortBindings> to change the default file name to BTDFProject.PortBindings.xml?  Are you now using PortBindingsMaster.xml?  If so, under the default names, PortBindingsMaster.xml will be transformed into PortBindings.xml.  It appears that your BTDFProject.PortBindings.xml does not exist or is not being created from the master file.  Do you have <IncludeMessagingBindings> set to true?

**Comment by tfabraham** [comment]
[malathy@1/19/2011]
thanks tfabraham.

You are correct.i have changed the default names of PortBindings.xml and PortBindingsMaster.xml to <Projectname>.PortBindings.xml and <Projectname>.PortBindingsMaster.xml respectively in their properties in the "BiztalkDeploymentframework.target" file. May i know how will this affect the MSI file  and its deployment.


My PortBinding file exist but i am unable to confidently tell that it is created from the PortBindinsMaster.xml, because i have created my PortBindings.xml file first for testing purpose by manually exporting it from admin console, 
then i created the PortBindingsMaster.xml by same means,then deleted the PortBindings.xml that was created prior to master binding.
Used "preprocess biztalk binding" option in the tool tab and created PortBindings.xml.

could you tell me what i did is correct ?

**Comment by tfabraham** [comment]
[tfabraham@1/19/2011]
Yes, it is working correctly -- you deleted the PortBindings.xml, ran Preprocess BizTalk Bindings and found that PortBindings.xml was re-created.  It is using your PortBindingsMaster.xml.  So now as long as you still have IncludeMessagingBindings set to true, during deployment you should see it attempt to import PortBindings.xml near the end of the process.

Your custom names for the binding files should not affect anything, though it's preferred that you leave them at the default names if possible.

**Comment by tfabraham** [comment]
[malathy@1/19/2011]
Thanks.

you are correct.During deployment it is attempting to import PortBindings.xml at the end of the process and not even in a single step during deployment it is making use of the PortBindingsMaster.xml

 tell me what could be done?

**Comment by tfabraham** [comment]
[tfabraham@1/19/2011]
If you need to override the default value of a property from BizTalkDeploymentFramework.targets, you should just include your own definition in your .btdfproj vs. modifying the Deployment Framework's .targets file.

Why do you believe that PortBindingsMaster.xml is not being used?  If you delete PortBindings.xml and run your deployment, and you find that PortBindings.xml has re-appeared, then that step is working properly.

**Comment by tfabraham** [comment]
[malathy@1/20/2011]
ok. Let me repeat the project from first.

now i have created the biztalk project and the Deploymentframework project. below is my .btdfproj file


----------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Deploy">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <Platform Condition="'$(Platform)' == ''">x86</Platform>
    <SchemaVersion>1.0</SchemaVersion>
    <ProjectName>MasterBindingProject</ProjectName>
    <ProjectVersion>1.0</ProjectVersion>
    <IncludeSchemas>True</IncludeSchemas>
    <IncludeOrchestrations>True</IncludeOrchestrations>
    <IncludeTransforms>True</IncludeTransforms>
    <IncludePipelines>False</IncludePipelines>
    <IncludeComponents>False</IncludeComponents>
    <IncludePipelineComponents>False</IncludePipelineComponents>
    <IncludeCustomFunctoids>False</IncludeCustomFunctoids>
    <IncludeVocabAndRules>False</IncludeVocabAndRules>
    <IncludeVirtualDirectories>False</IncludeVirtualDirectories>
    <IncludeMessagingBindings>True</IncludeMessagingBindings>
    <IncludeDeploymentTest>False</IncludeDeploymentTest>
    <Includelog4net>False</Includelog4net>
    <IncludeSSO>True</IncludeSSO>
    <IncludeEsbItineraries>False</IncludeEsbItineraries>
    <IncludeBam>False</IncludeBam>
    <IncludeInstallUtilForComponents>False</IncludeInstallUtilForComponents>
    <UsingMasterBindings>True</UsingMasterBindings>
    <ApplyXmlEscape>False</ApplyXmlEscape>
    <IncludeSettingsSpreadsheetInMsi>True</IncludeSettingsSpreadsheetInMsi>
    <IncludeCompsAndVDirsAsResources>False</IncludeCompsAndVDirsAsResources>
    <SkipIISReset>False</SkipIISReset>
    <StartApplicationOnDeploy>True</StartApplicationOnDeploy>
    <EnableAllReceiveLocationsOnDeploy>True</EnableAllReceiveLocationsOnDeploy>
    <StartReferencedApplicationsOnDeploy>True</StartReferencedApplicationsOnDeploy>
    <UseIsolatedAppDomain>False</UseIsolatedAppDomain>
    <EnableBizTalkExtendedLogging>False</EnableBizTalkExtendedLogging>
    <EnableBizTalkAssemblyValidation>False</EnableBizTalkAssemblyValidation>
    <EnableBizTalkCorrelationValidation>False</EnableBizTalkCorrelationValidation>
    <EnableBizTalkSchemaValidation>False</EnableBizTalkSchemaValidation>
  </PropertyGroup>
  <PropertyGroup>
    
    <ProductId>fa4d1e38-3196-468a-8225-c3c3064b10de</ProductId>
    <ProductUpgradeCode>878ae84c-e91c-4f84-8045-393176ed1d54</ProductUpgradeCode>
    <ProductName>MasterBindingProject for BizTalk</ProductName>
    <ProductVersion>1.0.0</ProductVersion>
    <Manufacturer>Deployment Framework User</Manufacturer>
    <PackageDescription>MasterBindingProject</PackageDescription>
    <PackageComments>MasterBindingProject</PackageComments>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DeploymentFrameworkTargetsPath>$(MSBuildExtensionsPath)\DeploymentFrameworkForBizTalk\5.0\</DeploymentFrameworkTargetsPath>
    <OutputPath>bin\Debug\</OutputPath>
    <DeployPDBsToGac>false</DeployPDBsToGac>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DeploymentFrameworkTargetsPath>$(MSBuildExtensionsPath)\DeploymentFrameworkForBizTalk\5.0\</DeploymentFrameworkTargetsPath>
    <OutputPath>bin\Release\</OutputPath>
    <DeployPDBsToGac>false</DeployPDBsToGac>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Server'">
    <DeploymentFrameworkTargetsPath>Framework\</DeploymentFrameworkTargetsPath>
    
    <DeployPDBsToGac>true</DeployPDBsToGac>
  </PropertyGroup>
  <ItemGroup>
	  <Schemas Include="MasterBindingProject.SampleProject.dll">
		  <LocationPath>E:\Malathi\MasterBindingProject\MasterBindingProject\MasterBindingProject.SampleProject\bin\Debug</LocationPath>
	  </Schemas>
	  <Transforms Include="MasterBindingProject.SampleProject.dll">
		  <LocationPath>E:\Malathi\MasterBindingProject\MasterBindingProject\MasterBindingProject.SampleProject\bin\Debug</LocationPath>
	  </Transforms>
	  <Orchestrations Include="MasterBindingProject.SampleProject.dll">
		  <LocationPath>E:\Malathi\MasterBindingProject\MasterBindingProject\MasterBindingProject.SampleProject\bin\Debug</LocationPath>
	  </Orchestrations>
  </ItemGroup>
  <Import Project="$(DeploymentFrameworkTargetsPath)BizTalkDeploymentFramework.targets" />
  
  <Target Name="CustomRedist">
  </Target>
</Project>
----------------------------------------------------------------------------

till now i have not created any binding file.when i try to deploy, i get the below mentioned error which is obvious,but i am not getting the application created in the biztalk admin console.


Starting build...
C:\Windows\Microsoft.NET\Framework\v3.5\MSBuild.exe "E:\Malathi\MasterBindingProject\MasterBindingProject\Deployment\MasterBindingProject.Deployment.btdfproj" /nologo /t:Deploy /p:Configuration=Release

Build started 1/20/2011 3:09:35 PM.
Project "E:\Malathi\MasterBindingProject\MasterBindingProject\Deployment\MasterBindingProject.Deployment.btdfproj" on node 0 (Deploy target(s)).
  Running on Windows V61
  Detected IIS 7
  Detected 64-bit OS
GetSoftwarePaths:
  Using .NET Framework Install Path 'C:\Windows\Microsoft.NET\Framework\v2.0.50727'.
  Using BizTalk Install Path 'C:\Program Files (x86)\Microsoft BizTalk Server 2009\'.
  Using Deployment Framework Install Path 'C:\Program Files (x86)\Deployment Framework for BizTalk\5.0\'.
  Using Deployment Framework Tools Path 'C:\Program Files (x86)\Deployment Framework for BizTalk\5.0\Framework\DeployTools'.
  Using BizTalk ESB Toolkit Install Path 'E:\ESBToolkit\'.
InitSettingsFilePath:
  Using settings file E:\Malathi\MasterBindingProject\MasterBindingProject\Deployment\EnvironmentSettings\local_settings.xml
ExportSettings:
  Environment Settings Spreadsheet to XML Exporter 1.5.1
  [http://EnvSettingsManager.codeplex.com]
  Copyright (C) 2007-10 Thomas F. Abraham.  All Rights Reserved.
  
  Importing from SettingsFileGenerator.xml...
  
  Output format is XmlPreprocess (multi-file).
  
  Exporting to local_settings.xml...
  Exporting to DEVL_settings.xml...
  Exporting to QA_settings.xml...
  Exporting to PROD_settings.xml...
  
  Finished.
InitializeAppName:
  BizTalk Application Name is MasterBindingProject
PreprocessBindings:
  Clearing file attributes for 'PortBindings.xml'.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : A task error has occured.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Message              = The resource string "FileNotFound.Exception" for the "SetValue" task cannot be found. Confirm that the resource name "FileNotFound.Exception" is correctly spelled, and the resource exists in the task's assembly.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Value                = MasterBindingProject
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : IgnoreNoMatchFailure = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Force                = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : XPath                = //ApplicationName
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Path                 = PortBindings.xml
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Namespaces           = <null>
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : 
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, Exception innerException, String resourceName, Object arg0, Object arg1)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatResourceString(String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.BaseXmlFileTask.OpenXmlFile(String path)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.SetValue.InternalExecute()
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.TaskBase.Execute()
Done Building Project "E:\Malathi\MasterBindingProject\MasterBindingProject\Deployment\MasterBindingProject.Deployment.btdfproj" (Deploy target(s)) -- FAILED.

Build FAILED.

"E:\Malathi\MasterBindingProject\MasterBindingProject\Deployment\MasterBindingProject.Deployment.btdfproj" (Deploy target) (1) ->
(PreprocessBindings target) -> 
  C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : A task error has occured.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Message              = The resource string "FileNotFound.Exception" for the "SetValue" task cannot be found. Confirm that the resource name "FileNotFound.Exception" is correctly spelled, and the resource exists in the task's assembly.
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Value                = MasterBindingProject
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : IgnoreNoMatchFailure = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Force                = True
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : XPath                = //ApplicationName
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Path                 = PortBindings.xml
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : Namespaces           = <null>
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error : 
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, Exception innerException, String resourceName, Object arg0, Object arg1)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatResourceString(String resourceName, Object[] args)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.BaseXmlFileTask.OpenXmlFile(String path)
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.XmlFile.SetValue.InternalExecute()
C:\Program Files (x86)\MSBuild\DeploymentFrameworkForBizTalk\5.0\BizTalkDeploymentFramework.targets(1049,4): error :    at Microsoft.Sdc.Tasks.TaskBase.Execute()

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.65

-------------------------------------------------------------------------
what should be my next step?

**Comment by tfabraham** [comment]
[UnknownUser@1/20/2011]

**Comment by tfabraham** [comment]
[UnknownUser@2/21/2013]

**Comment by tfabraham** [comment]
[UnknownUser@5/16/2013]

**Comment by tfabraham** [comment]
**Issue closed by _tfabraham_ with comment**
Please continue Discussion under Discussions thread
