### ISSUE TITLE
Issue: Rules import failing

### ISSUE THREAD

**Issue by tfabraham** [BTDF/DeploymentFramework#248]
Hi
 
This has suddenly popped up and i wondered if you have seen before:
 
BizTalk Rules Engine Policy/Vocabulary Deployment Tool v1.1.0.0
Copyright (C) 2005-2010 Scott Colestock, Thomas F. Abraham
 
Importing and publishing from file 'Repair.Core.Vocabularies.xml'...
Failed: Microsoft.RuleEngine.RuleEngineDeploymentDatabaseConnectionException: Er
ror encountered while connecting to database: "Initial Catalog=BizTalkRuleEngine
Db;Data Source=*\SQLMGT;Integrated Security=SSPI;". ---> System.Ty
peInitializationException: The type initializer for 'System.Data.SqlClient.SqlCo
nnection' threw an exception. ---> System.TypeInitializationException: The type
initializer for 'System.Data.SqlClient.SqlConnectionFactory' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Data.
SqlClient.SqlPerformanceCounters' threw an exception. ---> System.Configuration.
ConfigurationErrorsException: Configuration system failed to initialize ---> Sys
tem.Configuration.ConfigurationErrorsException: Unrecognized configuration secti
on startup. (C:\Program Files (x86)*\1.0\Deployment\Framework\De
ployTools\DeployBTRules.exe.Config line 3)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignor
eLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(Configurat
ionSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey
)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey
)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Intern
al.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sect
ionName)
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.Switch.InitializeConfigSettings()
   at System.Diagnostics.Switch.InitializeWithStatus()
   at System.Diagnostics.Switch.get_SwitchSetting()
   at System.Data.ProviderBase.DbConnectionPoolCounters..ctor(String categoryNam
e, String categoryHelp)
   at System.Data.SqlClient.SqlPerformanceCounters..ctor()
   at System.Data.SqlClient.SqlPerformanceCounters..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnectionFactory..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection..ctor()
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.BizTalk.RuleEngineExtensions.RuleSetDeploymentDriver.OpenConnect
ion(String location)
   --- End of inner exception stack trace ---
   at Microsoft.BizTalk.RuleEngineExtensions.RuleSetDeploymentDriver.OpenConnect
ion(String location)
   at Microsoft.BizTalk.RuleEngineExtensions.RuleSetDeploymentDriver.OpenConnect
ion()
   at Microsoft.BizTalk.RuleEngineExtensions.RuleSetDeploymentDriver.ImportAndPu
blishFileRuleStore(String fullFileName)
   at DeployBTRules.DeployRules.Main(String[] args)
 
 
Thanks
Simon

#### This work item was migrated from CodePlex
CodePlex work item ID: '9460'
Assigned to: 'tfabraham'
Vote count: '1'

**Comment by tfabraham** [comment]
[simonvinyl@6/19/2012]
UPDATE:
The probelm is todo with the below config setting in DeployTools\DeployBTRules.exe.config


Removing the config fixes the issue.

This link describes the problem and says the .exe needs to be recompliled.

http://social.msdn.microsoft.com/Forums/is/netfxappcompatprerelease/thread/a181e9b0-9d67-4d3c-80c4-11529196d3bc


Config section:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup useLegacyV2RuntimeActivationPolicy="true">
        <supportedRuntime version="v4.0" />
        <supportedRuntime version="v2.0.50727" />
    </startup>
</configuration>

Simon

**Comment by tfabraham** [comment]
[tfabraham@6/19/2012]
Thanks for the report and the update.  What version of BizTalk?

**Comment by tfabraham** [comment]
[UnknownUser@6/19/2012]

**Comment by tfabraham** [comment]
[UnknownUser@6/19/2012]
Resolved with changeset 68243.

**Comment by tfabraham** [comment]
[UnknownUser@2/21/2013]

**Comment by tfabraham** [comment]
[UnknownUser@5/16/2013]
