### ISSUE TITLE
SSOSettingsFileReader ReadString issue

### ISSUE THREAD

**Issue by tfabraham** [BTDF/DeploymentFramework#284]
Hi, after installing the new 5.1 beta 2 version, rebuilding and re-deploying my applications, I run into an error when using the SSOSettingsFileReader ReadString() function from within an orchestration or helper method.
Deployment itself does work fine, and also updates the SSO with the settings from the environment file.
We are using BizTalk 2010 on Windows Server 2008 R2 and SQL Server 2008 R2.
The message gets suspended, and there are 2 warnings and an error is in the event log:

Warning 1:
Access denied. The client user must be a member of one of the following accounts to perform this function.
 SSO Administrators: SSO Administrators
 SSO Affiliate Administrators: SSO Affiliate Administrators
 Application Administrators: BizTalk Server Administrators
 Application Users: -
 Additional Data: BIZTALK01\svcBTSHost ACME.BizTalk.Suppliers ACME.BizTalk.Suppliers Configuration Data
 
Warning 2:
_SSO AUDIT
 Function: GetConfigInfo ({56D74464-67EA-464d-A9D4-3EBBA4090010})
 Tracking ID: ac19397c-bd43-4a6e-ba26-7965365b5037
 Client Computer: biztalk01 (BTSNTSvc64.exe:17668)
 Client User: BIZTALK01\svcBTSHost
 Application Name: ACME.BizTalk.Suppliers
 Error Code: 0x80070005, Access is denied._

Error:
xlang/s engine event log entry: Uncaught exception (see the 'inner exception' below) has suspended an instance of service 'ACME.BizTalk.Suppliers.Orchestrations.SendMessageIncompleteEmailToSupplier(de02e883-11e9-bc53-38aa-2fa76114924a)'.
The service instance will remain suspended until administratively resumed or terminated. 
If resumed the instance will continue from its last persisted state and may re-throw the same unexpected exception.
InstanceId: ba893200-6598-456d-82ed-7acd253fdc22
Shape name: Configure port
ShapeId: e344d4b7-66d5-4e7e-9e29-3d8ebbaee3c9
Exception thrown from: segment 1, progress 9
Inner exception: Access denied. See the event log (on computer 'BIZTALK01') for more details.

      
Exception type: UnauthorizedAccessException
Source: SSOConfigStore.SSOConfigStore.1
Target Site: Void GetConfigInfo(System.String, System.String, Int32, Microsoft.BizTalk.SSOClient.Interop.IPropertyBag)
Help Link: 
The following is a stack trace that identifies the location where the exception occured

   at Microsoft.BizTalk.SSOClient.Interop.ISSOConfigStore.GetConfigInfo(String applicationName, String identifier, Int32 flags, IPropertyBag properties)
   at SSOSettingsFileManager.SSOSettingsFileReader.Read(String affiliateApplication)
   at SSOSettingsFileManager.SSOSettingsFileReader.ReadString(String affiliateApplication, String valueName)
   at ACME.BizTalk.Suppliers.Orchestrations.SendMessageIncompleteEmailToSupplier.segment1(StopConditions stopOn)
   at Microsoft.XLANGs.Core.SegmentScheduler.RunASegment(Segment s, StopConditions stopCond, Exception& exp)

The user which the host instance is running under is member of the BizTalk Application Users group, and after going back to the 5.0 version of the BTDF everything is working fine again.

Cheers,
Eldert Grootenboer

#### This work item was migrated from CodePlex
CodePlex work item ID: '10137'
Assigned to: 'tfabraham'
Vote count: '1'

**Comment by tfabraham** [comment]
[tfabraham@5/22/2013]
Caused by https://biztalkdeployment.codeplex.com/workitem/9551.  Will need to overload the methods to add an "useAdminMode" parameter instead of changing the default behavior.

**Comment by tfabraham** [comment]
[tfabraham@5/27/2013]
Simple workaround for now is to use v5.1 with the SSOSettingsFileReader.dll from v5.0.

**Comment by tfabraham** [comment]
[egrootenboer@5/28/2013]
Okay, good to know, will use that for now :-).

**Comment by tfabraham** [comment]
[UnknownUser@7/17/2013]

**Comment by tfabraham** [comment]
[UnknownUser@7/17/2013]
Resolved with changeset 73307.
