### ISSUE TITLE
Deploying via Azure DevOps struggles with SSO

### ISSUE THREAD

**Issue by fabsenet** [BTDF/DeploymentFramework#486]
Hi,

so this is no real issue with BTDF but I wanted to post here anyway to maybe get another idea.

If I run the quick deploy with my own user, everything just works ( i am local admin as well as sso admin)

If I run the msi-install + quick deploy via azure devops agent, everything runs as "nt authority\system". Installing everything succeeds, but updating the sso does not:

`System.UnauthorizedAccessException: Access denied. See the event log (on computer 'server1234') for more details.`
```text
2021-12-06T10:54:09.6782384Z DeploySSO:
2021-12-06T10:54:09.6783961Z   "C:\Program Files (x86)\ZES (Branch main Commit 3c77f57bc9015d43e5c59d30f4fb0493dd05b270)\3.0\Deployment\Framework\DeployTools\SSOSettingsFileImport.exe" "ZES" /settingsFile:"C:\Program Files (x86)\ZES (Branch main Commit 3c77f57bc9015d43e5c59d30f4fb0493dd05b270)\3.0\Deployment\EnvironmentSettings\Exported_QSSettings.xml" /userGroupName:"EUR\app_ve_biztalk_admin__x" /adminGroupName:"EUR\app_ve_biztalk_ssoadmin__x"
2021-12-06T10:54:20.3641024Z   Error persisting to SSO:
2021-12-06T10:54:20.3685712Z   System.UnauthorizedAccessException: Access denied. See the event log (on computer 'server1234') for more details.
2021-12-06T10:54:20.3686248Z   
2021-12-06T10:54:20.3691842Z      at Microsoft.BizTalk.SSOClient.Interop.ISSOAdmin.CreateApplication(String applicationName, String description, String contactInfo, String userGroupName, String adminGroupName, Int32 flags, Int32 numFields)
2021-12-06T10:54:20.3694164Z      at SSOSettingsFileManager.SSOHelper.CreateApp(String appName, String userGroup, String adminGroup)
2021-12-06T10:54:20.3698455Z      at SSOSettingsFileManager.SettingsFileImport.SaveSettingsToSSO(String affiliateAppName, String inSettings, String userGroupName, String adminGroupName)
2021-12-06T10:54:20.3700274Z      at SSOSettingsFileManager.SettingsFileImport.Main(String[] args)
2021-12-06T10:54:20.3858314Z C:\Program Files (x86)\ZES (Branch main Commit 3c77f57bc9015d43e5c59d30f4fb0493dd05b270)\3.0\Deployment\Framework\BizTalkDeploymentFramework.targets(1748,5): error MSB3073: The command ""C:\Program Files (x86)\ZES (Branch main Commit 3c77f57bc9015d43e5c59d30f4fb0493dd05b270)\3.0\Deployment\Framework\DeployTools\SSOSettingsFileImport.exe" "ZES" /settingsFile:"C:\Program Files (x86)\ZES (Branch main Commit 3c77f57bc9015d43e5c59d30f4fb0493dd05b270)\3.0\Deployment\EnvironmentSettings\Exported_QSSettings.xml" /userGroupName:"EUR\app_ve_biztalk_admin__x" /adminGroupName:"EUR\app_ve_biztalk_ssoadmin__x"" exited with code -1. [C:\Program Files (x86)\ZES (Branch main Commit 3c77f57bc9015d43e5c59d30f4fb0493dd05b270)\3.0\Deployment\ZES.Deployment.btdfproj]
2021-12-06T10:54:20.3869851Z Done Building Project "C:\Program Files (x86)\ZES (Branch main Commit 3c77f57bc9015d43e5c59d30f4fb0493dd05b270)\3.0\Deployment\ZES.Deployment.btdfproj" (UpdateOrchestration target(s)) -- FAILED.
2021-12-06T10:54:20.3910747Z 
2021-12-06T10:54:20.3911419Z Build FAILED.
```

I cannot add nt authority\system to my domain group of sso admins. I cannot use my own user, because it does not allow imersonation or batch processing logon and I cannot use my service account as it isn't an administrator.

Any ideas? I have no ideas left.

**Comment by tfabraham** [comment]
It sounds like the AzDO agent is running on a BizTalk server, but you have a domain vs. local group that controls the SSO admins? If it is a domain group, have you tried adding the computer account as THECOMPUTERNAME$?

**Comment by fabsenet** [comment]
that would be a good idea indeed and I requested it internally.
Also, I learned, you can run the devops agent as a real user instead of nt authority\system. The real user can be added to the AD sso group as well. But I am still waiting for the IT guys to fulfil my ticket requests.

**Comment by fabsenet** [comment]
okay so running the devops agent under a "normal" user account which has admin rights as well as which is a member of the sso admins group is the way to success here. getting the computer account into the sso admin group was not fast enough by our it service so I cannot say right now, if this would haven been an alternative way here.

**Comment by tfabraham** [comment]
Sounds good! Is this resolved then?

**Comment by fabsenet** [comment]
yes, its resolved i guess. we have the btdf build and release pipelines now running (quick deploy only).

feel free to mention me via @ next time, someone struggles with this here and I will try to help as well.
